const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openMain: () => ipcRenderer.send('open-main'),
  showNotification: (title, body) => ipcRenderer.send('show-notification', { title, body }),
  onPetMessage: (callback) => ipcRenderer.on('pet-message', (_event, message) => callback(message)),
  sendChat: (message, history) => ipcRenderer.invoke('pet-chat', { message, history }),
  figmaCapture: (params) => ipcRenderer.invoke('figma-capture', params),
  onChatResponse: (cb) => ipcRenderer.on('pet-chat-response', (_e, msg) => cb(msg)),
  triggerAction: (action) => ipcRenderer.send('pet-action', action),
  resizePetWindow: (w, h) => ipcRenderer.send('pet-resize', { width: w, height: h }),
  onDndPrompt: (cb) => ipcRenderer.on('pet-dnd-prompt', (_e, meetingTitle) => cb(meetingTitle)),
  respondDnd: (accepted) => ipcRenderer.send('pet-dnd-response', accepted),
  onDndEnd: (cb) => ipcRenderer.on('pet-dnd-end', () => cb()),
  startDrag: () => ipcRenderer.send('pet-start-drag'),
  dragMove: (x, y) => ipcRenderer.send('pet-drag-move', { x, y }),
  getTokenUsage: () => ipcRenderer.invoke('pet-token-usage'),
  getNextMeeting: () => ipcRenderer.invoke('pet-next-meeting'),
  getCalendarEvents: () => ipcRenderer.invoke('pet-calendar-events'),
  createCalendarEvent: (data) => ipcRenderer.invoke('pet-create-event', data),
  getEmails: () => ipcRenderer.invoke('pet-emails'),
  getTasks: () => ipcRenderer.invoke('pet-tasks'),
  composeEmail: (data) => ipcRenderer.invoke('pet-compose-email', data),
  getChatHistory: () => ipcRenderer.invoke('pet-chat-history'),
  contentStepNotification: (step, message) => ipcRenderer.send('content-step-notification', { step, message }),
  onPetMood: (cb) => ipcRenderer.on('pet-mood', (_e, mood) => cb(mood)),
  onThemeChange: (cb) => ipcRenderer.on('theme-changed', (_e, theme) => cb(theme)),
  setTheme: (theme) => ipcRenderer.send('set-theme', theme),
  getTheme: () => ipcRenderer.invoke('get-theme'),
  platform: process.platform,
});
